//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApDungKhuyenMai
    {
        public int id { get; set; }
        public Nullable<int> makhuyenmai { get; set; }
        public Nullable<int> maphong { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
