//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTour
    {
        public int madattour { get; set; }
        public int matour { get; set; }
        public int makhachhang { get; set; }
        public System.DateTime thoigiankhoihanh { get; set; }
        public System.DateTime thoigiantrove { get; set; }
        public int soluonghanhkhach { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TourDuLich TourDuLich { get; set; }
    }
}
