//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HanhLy
    {
        public int mahanhly { get; set; }
        public int maphieuvanchuyen { get; set; }
        public string ten { get; set; }
        public string dacdiem { get; set; }
    
        public virtual PhieuVanChuyenHanhLy PhieuVanChuyenHanhLy { get; set; }
    }
}
