//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementEntities : DbContext
    {
        public HotelManagementEntities()
            : base("name=HotelManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApDungKhuyenMai> ApDungKhuyenMais { get; set; }
        public virtual DbSet<CungCapDichVu> CungCapDichVus { get; set; }
        public virtual DbSet<DatTour> DatTours { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<Doan> Doans { get; set; }
        public virtual DbSet<DoiTac> DoiTacs { get; set; }
        public virtual DbSet<HanhLy> HanhLies { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NoiThat> NoiThats { get; set; }
        public virtual DbSet<PhieuDanhGia> PhieuDanhGias { get; set; }
        public virtual DbSet<PhieuDatPhong> PhieuDatPhongs { get; set; }
        public virtual DbSet<PhieuDatPhongChiTiet> PhieuDatPhongChiTiets { get; set; }
        public virtual DbSet<PhieuHuHongNoiThat> PhieuHuHongNoiThats { get; set; }
        public virtual DbSet<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }
        public virtual DbSet<PhieuSuDungDichVuChiTiet> PhieuSuDungDichVuChiTiets { get; set; }
        public virtual DbSet<PhieuSuDungThucPham> PhieuSuDungThucPhams { get; set; }
        public virtual DbSet<PhieuVanChuyenHanhLy> PhieuVanChuyenHanhLies { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
        public virtual DbSet<ThucPham> ThucPhams { get; set; }
        public virtual DbSet<TourDuLich> TourDuLiches { get; set; }
    }
}
