//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSuDungThucPham
    {
        public int maphieudatphong { get; set; }
        public int maphong { get; set; }
        public int mathucpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
    
        public virtual PhieuDatPhongChiTiet PhieuDatPhongChiTiet { get; set; }
        public virtual ThucPham ThucPham { get; set; }
    }
}
