//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuVanChuyenHanhLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuVanChuyenHanhLy()
        {
            this.HanhLies = new HashSet<HanhLy>();
        }
    
        public int maphieuvanchuyen { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public int maphieudatphong { get; set; }
        public int manhanvienphutrach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhLy> HanhLies { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
    }
}
