//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuHuHongNoiThat
    {
        public int maphieudatphong { get; set; }
        public int manoithat { get; set; }
        public Nullable<double> giatienden { get; set; }
    
        public virtual NoiThat NoiThat { get; set; }
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
    }
}
