//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSuDungDichVuChiTiet
    {
        public int madichvu { get; set; }
        public int maphieusudungdichvu { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> thoigiansudung { get; set; }
        public System.DateTime thoigianbatdau { get; set; }
        public Nullable<double> dongia { get; set; }
        public string tenkhachhang { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuSuDungDichVu PhieuSuDungDichVu { get; set; }
    }
}
