//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuDanhGias = new HashSet<PhieuDanhGia>();
            this.PhieuDatPhongChiTiets = new HashSet<PhieuDatPhongChiTiet>();
            this.PhieuHuHongNoiThats = new HashSet<PhieuHuHongNoiThat>();
            this.PhieuSuDungDichVus = new HashSet<PhieuSuDungDichVu>();
            this.PhieuVanChuyenHanhLies = new HashSet<PhieuVanChuyenHanhLy>();
        }
    
        public int maphieudatphong { get; set; }
        public string yeucaudatbiet { get; set; }
        public int sodemluutru { get; set; }
        public System.DateTime ngayden { get; set; }
        public int makhachhang { get; set; }
        public bool checkin { get; set; }
        public Nullable<int> nhanviencheckout { get; set; }
        public Nullable<int> nhanvienvesinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDanhGia> PhieuDanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDatPhongChiTiet> PhieuDatPhongChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuHuHongNoiThat> PhieuHuHongNoiThats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuVanChuyenHanhLy> PhieuVanChuyenHanhLies { get; set; }
    }
}
