//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSuDungDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuSuDungDichVu()
        {
            this.PhieuSuDungDichVuChiTiets = new HashSet<PhieuSuDungDichVuChiTiet>();
        }
    
        public int maphieu { get; set; }
        public Nullable<double> tongtien { get; set; }
        public int maletan { get; set; }
        public int maphieudatphong { get; set; }
    
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuSuDungDichVuChiTiet> PhieuSuDungDichVuChiTiets { get; set; }
    }
}
