//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public int sothutu { get; set; }
        public int madoan { get; set; }
        public string hoten { get; set; }
        public string cccd { get; set; }
    
        public virtual Doan Doan { get; set; }
    }
}
